-- One-file question import for the Supabase Dashboard.
--
-- Upload a CSV to public.question_import_staging. The trigger below upserts the
-- normalized question and replaces its answer choices in one transaction.

ALTER TABLE public.questions
ADD COLUMN IF NOT EXISTS source_key text;

CREATE UNIQUE INDEX IF NOT EXISTS questions_source_key_key
ON public.questions (source_key);

CREATE TABLE IF NOT EXISTS public.question_import_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_key text NOT NULL,
  subject_id uuid NOT NULL REFERENCES public.subjects(id) ON DELETE RESTRICT,
  question_number integer NOT NULL,
  question_text text NOT NULL,
  question_type text NOT NULL DEFAULT 'multiple_choice'
    CHECK (question_type IN ('multiple_choice', 'true_false', 'tree')),
  image_url text,
  answer_choices jsonb NOT NULL,
  explanation text,
  difficulty integer NOT NULL DEFAULT 2 CHECK (difficulty BETWEEN 1 AND 5),
  points integer NOT NULL DEFAULT 1,
  explanation_ja text,
  explanation_en text,
  explanation_vi text,
  imported_at timestamptz NOT NULL DEFAULT now(),
  CHECK (jsonb_typeof(answer_choices) = 'array')
);

ALTER TABLE public.question_import_staging ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admins_insert_question_import_staging"
ON public.question_import_staging;
CREATE POLICY "admins_insert_question_import_staging"
ON public.question_import_staging
FOR INSERT TO authenticated
WITH CHECK (public.is_admin());

GRANT INSERT ON TABLE public.question_import_staging TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.question_import_staging_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.sync_question_import_row()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_question_id uuid;
  correct_choice_count integer;
BEGIN
  IF jsonb_array_length(NEW.answer_choices) < 2 THEN
    RAISE EXCEPTION 'Question % must contain at least two answer choices', NEW.source_key;
  END IF;

  SELECT count(*)
  INTO correct_choice_count
  FROM jsonb_array_elements(NEW.answer_choices) AS item
  WHERE lower(coalesce(item->>'is_correct', 'false')) IN ('true', '1', 'yes');

  IF correct_choice_count <> 1 THEN
    RAISE EXCEPTION 'Question % must contain exactly one correct answer (found %)',
      NEW.source_key, correct_choice_count;
  END IF;

  INSERT INTO public.questions (
    source_key,
    subject_id,
    question_number,
    question_text,
    question_type,
    image_url,
    explanation,
    difficulty,
    points,
    explanation_ja,
    explanation_en,
    explanation_vi
  ) VALUES (
    NEW.source_key,
    NEW.subject_id,
    NEW.question_number,
    NEW.question_text,
    NEW.question_type,
    nullif(NEW.image_url, ''),
    nullif(NEW.explanation, ''),
    NEW.difficulty,
    NEW.points,
    nullif(NEW.explanation_ja, ''),
    nullif(NEW.explanation_en, ''),
    nullif(NEW.explanation_vi, '')
  )
  ON CONFLICT (source_key) DO UPDATE SET
    subject_id = EXCLUDED.subject_id,
    question_number = EXCLUDED.question_number,
    question_text = EXCLUDED.question_text,
    question_type = EXCLUDED.question_type,
    image_url = EXCLUDED.image_url,
    explanation = EXCLUDED.explanation,
    difficulty = EXCLUDED.difficulty,
    points = EXCLUDED.points,
    explanation_ja = EXCLUDED.explanation_ja,
    explanation_en = EXCLUDED.explanation_en,
    explanation_vi = EXCLUDED.explanation_vi
  RETURNING id INTO target_question_id;

  -- Update matching positions instead of deleting everything. This preserves
  -- answer-choice IDs referenced by historical practice/exam attempts.
  UPDATE public.answer_choices AS existing_choice
  SET
    choice_text = coalesce(
      nullif(incoming.item->>'text', ''),
      nullif(incoming.item->>'label', ''),
      'Choice ' || incoming.ordinality
    ),
    image_url = nullif(incoming.item->>'image_url', ''),
    is_correct = lower(coalesce(incoming.item->>'is_correct', 'false')) IN ('true', '1', 'yes')
  FROM jsonb_array_elements(NEW.answer_choices) WITH ORDINALITY AS incoming(item, ordinality)
  WHERE existing_choice.question_id = target_question_id
    AND existing_choice.sort_order = coalesce(
      nullif(incoming.item->>'sort_order', '')::integer,
      incoming.ordinality::integer
    );

  INSERT INTO public.answer_choices (
    question_id,
    choice_text,
    image_url,
    is_correct,
    sort_order
  )
  SELECT
    target_question_id,
    coalesce(nullif(incoming.item->>'text', ''), nullif(incoming.item->>'label', ''), 'Choice ' || incoming.ordinality),
    nullif(incoming.item->>'image_url', ''),
    lower(coalesce(incoming.item->>'is_correct', 'false')) IN ('true', '1', 'yes'),
    coalesce(nullif(incoming.item->>'sort_order', '')::integer, incoming.ordinality::integer)
  FROM jsonb_array_elements(NEW.answer_choices) WITH ORDINALITY AS incoming(item, ordinality)
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.answer_choices AS existing_choice
    WHERE existing_choice.question_id = target_question_id
      AND existing_choice.sort_order = coalesce(
        nullif(incoming.item->>'sort_order', '')::integer,
        incoming.ordinality::integer
      )
  );

  DELETE FROM public.answer_choices AS obsolete_choice
  WHERE obsolete_choice.question_id = target_question_id
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements(NEW.answer_choices) WITH ORDINALITY AS incoming(item, ordinality)
      WHERE obsolete_choice.sort_order = coalesce(
        nullif(incoming.item->>'sort_order', '')::integer,
        incoming.ordinality::integer
      )
    );

  -- Keep only the newest staging copy while making re-uploads idempotent.
  DELETE FROM public.question_import_staging
  WHERE source_key = NEW.source_key
    AND id IS DISTINCT FROM NEW.id;

  NEW.imported_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_question_import_row_trigger
ON public.question_import_staging;

CREATE TRIGGER sync_question_import_row_trigger
BEFORE INSERT OR UPDATE ON public.question_import_staging
FOR EACH ROW
EXECUTE FUNCTION public.sync_question_import_row();

COMMENT ON TABLE public.question_import_staging IS
  'Upload the CSV produced by scripts/prepare_question_import.py here. A trigger syncs questions and answer choices.';

-- The Admin panel renders PDF pages in the browser and uploads the optimized
-- images here. Public delivery is intentional because question images are
-- displayed to both signed-in and anonymous learners.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'question-images',
  'question-images',
  true,
  5242880,
  ARRAY['image/webp', 'image/png', 'image/jpeg']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "admins_select_question_images" ON storage.objects;
CREATE POLICY "admins_select_question_images"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'question-images' AND public.is_admin());

DROP POLICY IF EXISTS "admins_insert_question_images" ON storage.objects;
CREATE POLICY "admins_insert_question_images"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'question-images' AND public.is_admin());

DROP POLICY IF EXISTS "admins_update_question_images" ON storage.objects;
CREATE POLICY "admins_update_question_images"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'question-images' AND public.is_admin())
WITH CHECK (bucket_id = 'question-images' AND public.is_admin());

DROP POLICY IF EXISTS "admins_delete_question_images" ON storage.objects;
CREATE POLICY "admins_delete_question_images"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'question-images' AND public.is_admin());
